name: CICD-pipeline
env:
  S3_BUCKET_NAME      : "site-bucket-1e94b68"
  APPLICATION_NAME    : "StaticSite"
  DEPLOY_PACKAGE_NAME : "site_${{ github.sha }}"
  AWS_REGION_NAME     : "us-west-2"
  

on:
  push:
    branches: 
      - master

jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone git repo
        uses: actions/checkout@v1
